### PR TITLE
[T04] chore: add packages for auth, imgur and nodemon

### PR DESCRIPTION
**Pull request by tommy0311**

### CODE REVIEW

**Comment by tommy0311** [comment]
@dodouuu ready for review

**Comment by tommy0311** [comment]
@dodouuu ready for review

**Review by dodouuu — APPROVED** [review]
@tommy0311 approved

**Comment by tommy0311** [comment]
@dodouuu 
Next time, please use squash merge and confirm the subject does not break the rule. Thanks.

**Pull request merged**
